### PR TITLE
Tune model to be less sensitive and account for global binning

### PR DESCRIPTION
**Pull request by CermakM**
Current accuracy looks like this:
```
  draw-cross       0.95      0.95      0.95        37
        roll       0.87      0.96      0.92        28
       shake       0.92      0.81      0.86        27
       fever       0.81      0.84      0.82        25
 draw-circle       1.00      0.92      0.96        24
       floss       0.83      0.86      0.84        22
```

The fever and floss still make troubles but at least now we require those moves to be performed more exactly.

Signed-off-by: Marek Cermak <macermak@redhat.com>

modified:   v5_Gesture_Recognition_Serving.py
modified:   v5_Gesture_Recognition_Training.ipynb

### CODE REVIEW

**Comment by TreeinRandomForest** [comment]
@CermakM looks good - just so that I didn't miss anything, the two major changes are - 1) batch normalization, 2) non-uniform class weights (double for fever, floss and roll).

Cell [50] is very interesting. The model got fooled by "roll" only in 2/9 cases and in 1/9 case, it was ~50-50% between floss and roll. And maybe in those cases, if we were to run it by the gesture as "floss", it would be equally confident with floss which could then be used as a post-processing step (basically the 1-vs-all logic you mentioned this morning).

Everything looks good. I'll merge the PR.

**Comment by CermakM** [comment]
@TreeinRandomForest those are major changes to the model itself, then there is a change in the featurization -- concatenating globally binned input with gesture-specific binning.

**Comment by TreeinRandomForest** [comment]
@CermakM ah yes, just went through the code again and saw that. Combining the global and local binning makes sense to me. one feature that we might want to remove is length of the time-series since 

1) it occurs multiple times (once for each underlying measurement - 3 accelerations and 3 angular velocities) i.e. we get 6 identical, perfectly correlated features. this is because of how I wrote the featurize function

 2) it is highly dependent on the user and not the gesture. some users might get lazy and record short bursts and others might just keep going.

Does that make sense or do you think we should still keep one length around?

Thanks!

**Comment by CermakM** [comment]
Ah good point @TreeinRandomForest ! I didn't notice.. yes I think we should get rid of that, It might produce unwanted results, ie. instead of focusing on the `dance` itself, it can generalize based on the length. We might lose a little bit of information as some moves indeed take longer to perform, but it is as you said, users typically do not do just one cross or one circle, they do multiple, so this information gets lost anyway I guess.

As a side note, it might be worth doing some simple variance and correlation analysis of those features after the binning.

**Pull request merged**
