### PR TITLE
pre load model

### PR DESCRIPTION
**Pull request by durandom**
trying to pre-load the model.

Did not test it, because I dont know how :/

https://gist.github.com/bbrowning/4e075f420ce1a62b8e8310afb31c64b9 has some output from the previous version which loads the model on every request :(

@vpavlin @CermakM please have a look

### CODE REVIEW

**Comment by durandom** [comment]
regarding threading. is flask multithreaded anyway?
but now I think it does modify globals after the server is started anymore

**Comment by CermakM** [comment]
This will throw an error: 
`ValueError: Tensor Tensor("dense_3/LogSoftmax:0", shape=(?, 6), dtype=float32) is not an element of this graph.`

I like your solution, tho.. I like it, because I initially wrote the same one .. check out the commits before/after this one: https://github.com/rhdemo/2019-demo4-ai/commit/9d6df005d963e3bff8006df9437194df6e11abd2 


This is an error which we've encountered before and it was solved by that commit.

**Comment by CermakM** [comment]
As far as the testing is concerned, the approach is somewhat documented in the README, but it should be possible to simply install virtual environment (`pipenv install && pipenv shell`) and run the serving `./v5_*Serving.py`

**Comment by CermakM** [comment]
@durandom PTAL at #21

**Comment by durandom** [comment]
@CermakM @TreeinRandomForest @MichaelClifford is there a way to work around

```
ValueError: Tensor Tensor("dense_3/LogSoftmax:0", shape=(?, 6), dtype=float32) is not an element of this graph.
```

?
Because loading the model on every inference request seems to be the culprit of the pods crashing

**Comment by durandom** [comment]
closing if favour of turning off threading

**Pull request closed without merging**
